### ISSUE TITLE
Idea: Make xbacklight-auto Not Blocking the Webcam Between Frames

### ISSUE THREAD

**Issue by drocheam** [raptor8134/xbacklight-auto#3]
By moving camera_init and camera_close inside the main loop (before sleep(time)) you could make the whole program not blocking your webcam between frames. So the camera is only in use for a minor part of the time. 

When you don't abort execution on errors, the program just tries again in the next iteration.

This has the nice side effect that you can use your webcam normally while xbacklight-auto runs in the background, because it now only takes a picture if the webcam is available.

However, there are some issues: 
* First, the program now doesn't exit on errors. 
* The other one is that there is a slight chance that your webcam is in use by xbacklight-auto while another program tries to access it (e.g when starting Zoom). This may confuse users or make programs accessing the webcam unusable. Although I don't know what would happen exactly.

Because this has its advantages and disadvantages, this is more a design decision than a feature request/issue.

**Comment by raptor8134** [comment]
I'm going to make a new branch with this type of design, janky version coming in a few minutes.

**Comment by drocheam** [comment]
Works excellent for me. 👌
I tested `-t 1` for an unrealistic frame rate. Programs like Zoom, Cheese (Webcam Viewer) or an online webcam tester seem to handle it quite well when the webcam is in use temporarily. When clicking "Start Video" in Zoom it sometimes refuses to use the webcam while it's in use by xbacklight-auto, but you can just click multiple times until it does. Cheese just seems to wait until the camera becomes available.
Normal settings are like `-t 10`, so this should happen a lot less often.

I've only seen the bruh1-case, but bruh2 should also work (like it did before).

**Comment by raptor8134** [comment]
Dang it I wasn't supposed to leave those printfs there, but it's good to know it works for you

**Comment by drocheam** [comment]
Check my fork's main branch for a cleaned up version. Got rid of the bruhs and the unnecessary if-case and the buffer variable.

Would open a pull request, but for some reason github incorrectly compares between your second branch and my fork's main branch.

**Comment by raptor8134** [comment]
Alright we are merged
